name: lua-language-server
base: core24
version: '3.9.3'
license: MIT
summary:  A language server that offers Lua language support
description: |
  The Lua language server provides various language features
  for Lua to make development easier and faster.
  With nearly a million installs in Visual Studio Code,
  it is the most popular extension for Lua language support.

confinement: strict

apps:
  lua-language-server:
    command: bin/lua-language-server
    plugs:
      - home
environment:
  LLS_LOG_PATH: $SNAP_USER_DATA/log
  LLS_META_PATH: $SNAP_USER_DATA/meta

parts:
  lua-lsp:
    plugin: dump
    build-attributes:
     - enable-patchelf
    source:
      - to amd64: "https://github.com/LuaLS/lua-language-server/releases/download/$CRAFT_PROJECT_VERSION/lua-language-server-$CRAFT_PROJECT_VERSION-linux-x64.tar.gz"
      - else: "https://github.com/LuaLS/lua-language-server/releases/download/$CRAFT_PROJECT_VERSION/lua-language-server-$CRAFT_PROJECT_VERSION-linux-$CRAFT_ARCH_BUILD_FOR.tar.gz"
    source-type: tar
platforms:
  amd64:
  arm64:
