name: lua-language-server
base: core24
version: '3.9.3'
summary:  A language server that offers Lua language support - programmed in Lua 
description: |
  The Lua language server provides various language features for Lua to make development easier and faster. With nearly a million installs in Visual Studio Code, it is the most popular extension for Lua language support.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  lua-language-server:
    command: bin/lua-language-server
    plugs:
      - network-bind
      - home
environment:
  LLS_LOG_PATH: $SNAP_USER_DATA/log
  LLS_META_PATH: $SNAP_USER_DATA/cache

parts:
  lua-lsp:
    plugin: dump
    #source: https://github.com/LuaLS/lua-language-server/releases/download/$CRAFT_PROJECT_VERSION/lua-language-server-$CRAFT_PROJECT_VERSION-linux-$PLATFORM.tar.gz
    #source: https://github.com/LuaLS/lua-language-server/releases/download/$CRAFT_PROJECT_VERSION/lua-language-server-$CRAFT_PROJECT_VERSION-linux-x64.tar.gz
    source:
      - to amd64: "https://github.com/LuaLS/lua-language-server/releases/download/$CRAFT_PROJECT_VERSION/lua-language-server-$CRAFT_PROJECT_VERSION-linux-x64.tar.gz"
      - else: "https://github.com/LuaLS/lua-language-server/releases/download/$CRAFT_PROJECT_VERSION/lua-language-server-$CRAFT_PROJECT_VERSION-linux-$CRAFT_ARCH_BUILD_FOR.tar.gz"
    source-type: tar
platforms:
  # Unfortunately does not work as expected
  amd64: 
  arm64:
